import {
  AutomationWorkflow,
  CommandExecution,
  DatabaseNode,
  SocialCampaign,
  TunnelNode,
} from '../types/amarco';

export const INITIAL_TUNNEL_NODES: TunnelNode[] = [
  {
    id: 'ch-zurich-01',
    city: 'Zurich',
    country: 'Switzerland',
    flag: '🇨🇭',
    ip: '185.220.101.42',
    latencyMs: 14,
    cipher: 'ChaCha20-Poly1305 / WireGuard',
    loadPercent: 28,
  },
  {
    id: 'is-reykjavik-02',
    city: 'Reykjavik',
    country: 'Iceland',
    flag: '🇮🇸',
    ip: '194.38.20.114',
    latencyMs: 26,
    cipher: 'AES-256-GCM / Hardware ACC',
    loadPercent: 19,
  },
  {
    id: 'sg-singapore-03',
    city: 'Singapore',
    country: 'Singapore',
    flag: '🇸🇬',
    ip: '103.253.144.89',
    latencyMs: 42,
    cipher: 'Shadowsocks-2022 / AEAD',
    loadPercent: 34,
  },
  {
    id: 'de-frankfurt-04',
    city: 'Frankfurt',
    country: 'Germany',
    flag: '🇩🇪',
    ip: '141.98.252.19',
    latencyMs: 19,
    cipher: 'WireGuard v2 Strict',
    loadPercent: 41,
  },
  {
    id: 'jp-tokyo-05',
    city: 'Tokyo',
    country: 'Japan',
    flag: '🇯🇵',
    ip: '133.242.18.66',
    latencyMs: 65,
    cipher: 'AES-256-GCM / Ephemeral Keys',
    loadPercent: 22,
  },
];

export const INITIAL_CAMPAIGNS: SocialCampaign[] = [
  {
    id: 'camp-global-launch',
    name: 'Global Autonomous Agent Rollout 2026',
    targetObjective: 'Establish cross-platform viral dominance for desktop agent capabilities',
    platforms: ['X / Twitter', 'LinkedIn', 'Instagram', 'Reddit'],
    status: 'active',
    totalReach: '248,500 impressions',
    encryptedTunnelUsed: 'Zurich (CH-SEC-01) Residential Proxy',
    lastUpdated: '12m ago',
    posts: [
      {
        id: 'post-1',
        platform: 'X / Twitter',
        content: 'Autonomous workflows don’t wait for manual clicks. AMARCO executes cross-application directives locally and secretly across worldwide clusters. #AI #AutonomousAgent #ZeroLeak',
        scheduledTime: 'Published · 24m ago',
        status: 'published',
        stealthProxy: '185.220.101.42 (Zurich)',
        engagement: { views: '18.4K', likes: '1.2K', reposts: '420' },
      },
      {
        id: 'post-2',
        platform: 'LinkedIn',
        content: 'Why executive desktop automation requires a zero-trust encrypted tunnel: Introducing sovereign computing architecture that routes cloud queries while preserving 100% local cryptographic privacy.',
        scheduledTime: 'Today at 14:30 GMT',
        status: 'scheduled',
        stealthProxy: '194.38.20.114 (Reykjavik)',
      },
      {
        id: 'post-3',
        platform: 'Reddit',
        content: 'Showcasing our offline-first desktop orchestrator that performs tasks across local apps and cloud databases without exposing device telemetry.',
        scheduledTime: 'Published · 1h ago',
        status: 'published',
        stealthProxy: '103.253.144.89 (Singapore)',
        engagement: { views: '32.1K', likes: '890', reposts: '144' },
      },
    ],
  },
  {
    id: 'camp-cloud-security',
    name: 'Stealth Intelligence & Zero-Trace Briefing',
    targetObjective: 'Target tech founders & data engineers on privacy-preserving automation',
    platforms: ['X / Twitter', 'LinkedIn'],
    status: 'active',
    totalReach: '89,200 impressions',
    encryptedTunnelUsed: 'Reykjavik (IS-SEC-02) Zero-Log Node',
    lastUpdated: '45m ago',
    posts: [
      {
        id: 'post-4',
        platform: 'X / Twitter',
        content: 'When your desktop AI agent speaks, the network hears nothing. Full encrypted tunnel encapsulation with ChaCha20 cipher. Total privacy is not a feature; it is an invariant.',
        scheduledTime: 'Scheduled for 18:00',
        status: 'scheduled',
        stealthProxy: '194.38.20.114 (Reykjavik)',
      },
    ],
  },
];

export const INITIAL_DATABASES: DatabaseNode[] = [
  {
    id: 'db-pg-frankfurt',
    name: 'Master PostgreSQL Cloud Cluster',
    provider: 'PostgreSQL Cloud',
    region: 'Frankfurt (eu-central-1)',
    recordsCount: 1420500,
    lastSynced: '2m ago',
    status: 'connected',
    tables: ['users', 'social_metrics', 'task_telemetry', 'auth_tokens', 'campaign_logs'],
    stealthTunnelActive: true,
  },
  {
    id: 'db-bq-analytics',
    name: 'Google BigQuery Global Warehouse',
    provider: 'Google BigQuery',
    region: 'Global Multi-Region',
    recordsCount: 89400000,
    lastSynced: '14m ago',
    status: 'connected',
    tables: ['market_events', 'aggregated_impressions', 'threat_intelligence', 'node_pings'],
    stealthTunnelActive: true,
  },
  {
    id: 'db-supabase-edge',
    name: 'Supabase Global Realtime Edge',
    provider: 'Supabase Global',
    region: 'Singapore (ap-southeast-1)',
    recordsCount: 384000,
    lastSynced: 'Just now',
    status: 'connected',
    tables: ['active_sessions', 'workflow_triggers', 'agent_heartbeats'],
    stealthTunnelActive: true,
  },
  {
    id: 'db-local-vault',
    name: 'AMARCO Encrypted Local NVMe Vault',
    provider: 'Encrypted Local SQLite',
    region: 'Local Machine (Air-Gapped Mirror)',
    recordsCount: 290120,
    lastSynced: 'Real-time',
    status: 'connected',
    tables: ['secure_keys', 'voice_patterns', 'offline_knowledge', 'audit_hash_chain'],
    stealthTunnelActive: true,
  },
];

export const INITIAL_WORKFLOWS: AutomationWorkflow[] = [
  {
    id: 'wf-viral-blast',
    title: 'Cross-Platform Social Viral Broadcast',
    category: 'social',
    description: 'Generates tailored copy, rotates residential proxies, posts to X, LinkedIn, and Reddit, and logs metrics.',
    trigger: 'Voice command or daily at 09:00 GMT',
    appsInvolved: ['X / Twitter', 'LinkedIn', 'Reddit', 'Encrypted Tunnel', 'Content Engine'],
    autoExecute: true,
    runsCount: 38,
    lastRunTime: '2 hours ago',
    status: 'active',
    stepsPreview: [
      'Tunnel routing through Zurich',
      'Generate platform-specific hook variations',
      'Transmit with staggered randomized delays',
      'Collect real-time sentiment telemetry',
    ],
  },
  {
    id: 'wf-db-replication',
    title: 'Zero-Trace Worldwide DB Replication',
    category: 'database',
    description: 'Syncs cloud PostgreSQL, BigQuery, and local encrypted vault via mutual TLS and wireguard tunnels.',
    trigger: 'Every 60 minutes or on demand',
    appsInvolved: ['PostgreSQL', 'BigQuery', 'Local Vault', 'WireGuard'],
    autoExecute: true,
    runsCount: 142,
    lastRunTime: '14 mins ago',
    status: 'active',
    stepsPreview: [
      'Verify zero DNS or IP leaks',
      'Diff local ledger against remote Merkle root',
      'Encrypted stream replication',
      'Memory purge on completion',
    ],
  },
  {
    id: 'wf-stealth-intel',
    title: 'Global Stealth Market Intelligence',
    category: 'intelligence',
    description: 'Scrapes global competitors and unrestricted news sources worldwide without exposing user coordinates.',
    trigger: 'Voice prompt: "Gather market intel"',
    appsInvolved: ['Headless Scraper', 'Tor / WireGuard', 'NLP Parser', 'Local Vault'],
    autoExecute: false,
    runsCount: 19,
    lastRunTime: 'Yesterday',
    status: 'standby',
    stepsPreview: [
      'Scramble browser fingerprint & TLS ClientHello',
      'Extract unrestricted content across 12 countries',
      'Deduplicate and summarize key signals',
      'Archive to local encrypted database',
    ],
  },
  {
    id: 'wf-local-sanitizer',
    title: 'Local Privacy Shield & Telemetry Shredder',
    category: 'security',
    description: 'Overwrites temporary cache files, kills idle network sockets, and refreshes residential proxy identity.',
    trigger: 'Every system idle or manual override',
    appsInvolved: ['Local FS', 'Kernel Memory', 'Privacy Shield'],
    autoExecute: true,
    runsCount: 88,
    lastRunTime: '35 mins ago',
    status: 'active',
    stepsPreview: [
      'Zero-fill ephemeral buffers',
      'Reset virtual hardware UUIDs',
      'Renew WireGuard cryptographic handshake',
    ],
  },
];

export const INITIAL_AUDIT_LOGS = [
  {
    id: 'aud-001',
    timestamp: '2026-09-29T16:20:12Z',
    commandSnippet: 'Sync BigQuery analytics and Postgres cluster via encrypted tunnel',
    operator: 'Master Executive',
    executionMode: 'cloud-neural',
    durationMs: 742,
    tunnelNode: 'Zurich (185.220.101.42)',
    status: 'SUCCESS' as const,
    hashSignature: '0x8f2a...c391',
  },
  {
    id: 'aud-002',
    timestamp: '2026-09-29T15:45:00Z',
    commandSnippet: 'Broadcast autonomous launch announcement across X, LinkedIn, Reddit',
    operator: 'Master Executive',
    executionMode: 'local-stealth',
    durationMs: 890,
    tunnelNode: 'Reykjavik (194.38.20.114)',
    status: 'SECURE_COMPLETED' as const,
    hashSignature: '0x4d1b...9a0e',
  },
  {
    id: 'aud-003',
    timestamp: '2026-09-29T14:12:38Z',
    commandSnippet: 'Scramble local identity fingerprint and establish WireGuard kill-switch',
    operator: 'Master Executive',
    executionMode: 'offline-isolated',
    durationMs: 410,
    tunnelNode: 'Singapore (103.253.144.89)',
    status: 'ISOLATED' as const,
    hashSignature: '0x17fa...bb62',
  },
];

export const INITIAL_EXECUTION: CommandExecution = {
  id: 'exec-init-01',
  timestamp: new Date().toISOString(),
  command: 'Deploy global multi-platform campaign and verify encrypted tunnel routing across worldwide databases',
  voiceTriggered: true,
  mode: 'cloud-neural',
  status: 'completed',
  thought: 'AMARCO received top-level command. Validating encrypted tunnel parameters (WireGuard v2 with ChaCha20-Poly1305). Outbound routing masked to Zurich residential exit node 185.220.101.42. Orchestrating parallel dispatch to social media queues and remote database synchronization.',
  securityProfile: {
    tunnelProtocol: 'WireGuard v2 / AES-256-GCM',
    exitNode: 'Zurich (CH-SEC-01)',
    maskedIp: '185.220.101.42',
    identityProtection: '100% Cloaked (Zero-Leak Verified)',
  },
  steps: [
    {
      id: 'step-1',
      title: 'Initialize Encrypted Tunnel & Cloak IP',
      application: 'Encrypted Tunnel',
      action: 'Lock outbound network interface to WireGuard tunnel gateway',
      status: 'completed',
      detail: 'Assigned masked IP 185.220.101.42 (Switzerland). DNS leak test: 0 leaks.',
      durationMs: 120,
    },
    {
      id: 'step-2',
      title: 'Synthesize & Dispatch Cross-Platform Campaign',
      application: 'Social Media Engine',
      action: 'Target X/Twitter, LinkedIn, and Reddit with stealth proxies',
      status: 'completed',
      detail: 'Broadcasted to 3 platforms with randomized jitter. Total initial reach: 48.5K impressions.',
      durationMs: 340,
    },
    {
      id: 'step-3',
      title: 'Query & Replicate Worldwide Cloud Database',
      application: 'PostgreSQL Cloud & BigQuery',
      action: 'Synchronize 142,000 analytics records into encrypted local mirror',
      status: 'completed',
      detail: 'Encrypted TLS socket completed in 28ms. Local NVMe vault synchronized.',
      durationMs: 290,
    },
    {
      id: 'step-4',
      title: 'Automated Post-Flight Verification',
      application: 'Audit Ledger',
      action: 'Cryptographically sign transaction record to immutable local chain',
      status: 'completed',
      detail: 'Hash 0x8f2a...c391 sealed. Zero forensic artifacts left in unencrypted RAM.',
      durationMs: 80,
    },
  ],
  artifact: {
    type: 'campaign',
    title: 'Autonomous Multi-App Execution Dossier',
    summary: 'AMARCO completed seamless end-to-end execution across social platforms, cloud databases, and privacy tunnels with zero manual intervention.',
    content: `### Executive Mission Report: Autonomous Campaign & Database Sync\n\n**Mission Status:** 100% COMPLETED (Zero Manual Intervention)\n**Security Posture:** FULL ENCRYPTED TUNNEL ACTIVE\n\n#### 1. Social Media Broadcast\n- **Target Platforms:** X (Twitter), LinkedIn, Reddit, Instagram\n- **Stealth Gateway:** Zurich Residential Proxy (185.220.101.42)\n- **Performance:** 3 posts queued, 1 live. Immediate engagement: +1,240 likes, +420 shares.\n- **Content Theme:** Sovereign desktop intelligence & encrypted workflow automation.\n\n#### 2. Cloud Database Synchronization\n- **Target Systems:** PostgreSQL Frankfurt & Google BigQuery Global\n- **Replicated Records:** 142,890 rows synchronized\n- **Data Integrity:** SHA-256 Merkle root matched\n- **Host Identity Exposure:** 0% (Cloaked via WireGuard)\n\n#### 3. Privacy & Tunnel Verification\n- **Virtual Masked IP:** \`185.220.101.42\`\n- **DNS Resolvers:** Zero-knowledge cryptographic resolver\n- **Kill-Switch:** Armed and standing by`,
    metrics: [
      { label: 'Precision Rate', value: '100%' },
      { label: 'Latency', value: '28ms' },
      { label: 'Network Footprint', value: '0 Trace' },
    ],
  },
  spokenResponse: 'All instructions fulfilled in real time. Social media campaigns are live and worldwide cloud databases are synchronized under complete encrypted stealth.',
  executionTimeMs: 830,
};
